### ISSUE TITLE
Lack of integrity verification of downloaded external dependencies

### ISSUE THREAD

**Issue by mensfeld** [ntkme/embedded-host-ruby#1]
Hey,

My name is Maciej Mensfeld and I run a research security project called WhiteSource Diffend.io.

I've noticed, that this library downloads some external resources and uses them. While it's a totally common pattern, what is lacking here is integrity verification.

You could verify the integrity of the downloaded files before using them by comparing the files hashes to a hardcoded, expected files hashes.

This is essentially what package managers do to verify the integrity of downloaded packages.

Doing this would prevent attack scenarios in which `sass-embedded` is manipulated.

Have a great day :)

ref: https://my.diffend.io/gems/sass-embedded/0.1.0/page/1#d2h-090432-2851

**Comment by ntkme** [comment]
The dart-sass-embedded is not stable yet, so currently it always downloads the latest release binary from https://github.com/sass/dart-sass-embedded/releases. Because the latest release is changing I cannot hard code a checksum.

This will be reconsidered once the dependency has entered a stable state, closing for now.
